[package]
name = "game_engine"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"] 

[dependencies]
wasm-bindgen = "0.2.99"
rand = { version = "0.8" }
getrandom = { version = "0.2", features = ["js"] }
web-sys = { version = "0.3.76", features = ["Window"] }
